const Photos = [
    {
        id:1,
        name: "Photo-1",
        category:"natural",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1658679684720-12041e151b90?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDUyfGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:2,
        name: "Photo-2",
        category:"natural",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1658816682611-00db7e16ca8a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDEwfDZzTVZqVExTa2VRfHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:3,
        name: "Photo-3",
        category:"natural",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1582765805106-0ff2380b9596?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDE1fDZzTVZqVExTa2VRfHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:4,
        name: "Photo-4",
        category:"natural",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1658518815743-af2e2ff993af?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDU3fGJvOGpRS1RhRTBZfHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:5,
        name: "Photo-5",
        category:"natural",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1542856391-010fb87dcfed?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDIxfEZ6bzN6dU9ITjZ3fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:6,
        name: "Photo-6",
        category:"natural",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1658901205299-9d1c95b1eb3a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8RnpvM3p1T0hONnd8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:7,
        name: "Photo-7",
        category:"minimilist",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Zmxvd2Vyc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:8,
        name: "Photo-8",
        category:"minimilist",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1552083375-1447ce886485?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEyfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:9,
        name: "Photo-9",
        category:"minimilist",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1592492159418-39f319320569?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:10,
        name: "Photo-10",
        category:"minimilist",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1556139902-7367723b7e9e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE2fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:11,
        name: "Photo-11",
        category:"minimilist",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1592587445145-04498cbba81c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEwfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:12,
        name: "Photo-12",
        category:"minimilist",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:13,
        name: "Photo-13",
        category:"classic",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1619963258837-b83f3406cfcd?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDEwfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:14,
        name: "Photo-14",
        category:"classic",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1658901742266-2b1c9a7f84f0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDV8RnpvM3p1T0hONnd8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:15,
        name: "Photo-15",
        category:"classic",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bXVzaWN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:16,
        name: "Photo-16",
        category:"classic",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1506157786151-b8491531f063?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fG11c2ljfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:17,
        name: "Photo-17",
        category:"classic",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1468234847176-28606331216a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDd8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:18,
        name: "Photo-18",
        category:"classic",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1658901205299-9d1c95b1eb3a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHx0b3BpYy1mZWVkfDR8RnpvM3p1T0hONnd8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:19,
        name: "Photo-1",
        category:"natural",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1496024840928-4c417adf211d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGhvbGl8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    },
    {
        id:20,
        name: "Photo-20",
        category:"minimilist",
        price:"NOT INTRESTED",
        description:"Hello this is dummy text , only for testing text is dummy only for testing purpose not related to any thing else.",
        img: "https://images.unsplash.com/photo-1485955900006-10f4d324d411?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
    }
];

export default Photos;